language: r
cache: packages
warnings_are_errors: true
sudo: true
r_packages:
  - covr
  - ExPosition
r_binary_packages:
  - topicmodels
env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes"

before_install:
  - sudo apt-get install libgsl0-dev libtbb-dev r-cran-rcpp
  - Rscript -e 'install.packages(c("devtools", "topicmodels", "tm"))'
  
after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
    slack: quanteda:W4x9WmNKqE7kVtkKZDWld7IP
